name: Helpers NuGet Generation

on:
  push:
    paths:
      - 'XControls.Helpers/**'
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |
          cd XControls.Helpers/
          dotnet pack XControls.Helpers.csproj -c Release -o out  

      - name: Push generated package to GitHub registry
        run: |
          cd XControls.Helpers/out/
          dotnet nuget push **/*.nupkg -k oy2ke5fy427zjikjvfxqfkxfxm3oh7ce5jaorskkkwdomi --skip-duplicate --no-symbols true

