name: NotificationBanner NuGet Generation

on:
  push:
    paths:
      - '.github/workflows/NotificationBanner.yml'
      - 'XControls.NotificationBanner/XControls.NotificationBanner.csproj'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET @ Latest
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |     
            3.1.x
            6.0.x 
          include-prerelease: true
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGETKEY}}        
          
      - name: Build solution and generate NuGet package
        run: |
          cd XControls.NotificationBanner/
          dotnet pack XControls.NotificationBanner.csproj -c Release -o out  

      - name: Push generated package to GitHub registry
        run: |
          cd XControls.NotificationBanner/out/
          dotnet nuget push **/*.nupkg -k ${{secrets.NUGETKEY}} --no-symbols true
