name: Utilities NuGet Generation

on:
  push:
    paths:
      - '.github/workflows/Utilities.yml'
      - 'XControls.Utilities/XControls.Utilities.csproj'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |     
            3.1.x
            6.0.x 
          include-prerelease: true
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |
          cd XControls.Utilities/
          dotnet pack XControls.Utilities.csproj -c Release -o out  
      - name: Push generated package to GitHub registry
        run: |
          cd XControls.Utilities/out/
          dotnet nuget push **/*.nupkg -k ${{secrets.NUGETKEY}} --no-symbols true
